# Connect to postgres
postgres:
  host: postgres
  port: 5432
  database: scoredb
  user: scoreuser
  password: scorepass
  schema: public
  table_name: tbl_output_scoring

# Connect to MinIO
minio:
  endpoint: minio:9990
  access_key: minio
  secret_key: minio123
  bucket: clean-202605
